### ISSUE TITLE
Authentication codes wrong in new time zone

### ISSUE THREAD

**Issue by fidian** [JumpMaster/PebbleAuth#13]
I'm in a different time zone for a while and now my phone's codes does not match the ones generated by my watch.  I read that a time zone is needed to make the calculations properly for MFA.  Do you think this is the issue?  If so, how can I fix things?

**Comment by JumpMaster** [comment]
Hi!

The JS running in the Pebble app sends the timezone offset from GMT to the watch on boot.  I don't know how the pebble app calculates it but I'd start by checking the timezone is correct for your new location.

Previously after changing timezone I have to reboot my phone before the pebble app realized.  This isn't the case anymore but I'm not sure if that's due to a Pebble or an Android update.

Kev

**Comment by fidian** [comment]
Restarting my phone fixed the timezone issue.  I think this might be worthy of a FAQ in the README?
